### ISSUE TITLE
Mean Well RSP-500-24 support

### ISSUE THREAD

**Issue by Majawat** [jon-harper/OmniBox#11]
The mounting holes for the Mean Well RSP-500-24 do not match the current Core files. It is larger than the current files, taking up majority of the lower base.

Bonus if there was a way to add an extra fan to the case to fool down this large PSU.

**Comment by jon-harper** [comment]
> The mounting holes for the Mean Well RSP-500-24 do not match the current Core files. It is larger than the current files, taking up majority of the lower base.

Oof, my bad for not considering this. I even have an SE-450-24 on a printer and knew the mounting holes are not universal.

I'll get a CAD file and get to work on this.

> Bonus if there was a way to add an extra fan to the case to fool down this large PSU.

Couple of thoughts:

- The new generic rear panels have 60mm exhaust fan that might help.
- I will look at a 40mm mounted low on the rear panel (next to the power connector), as well.
- Alternatively, a big ol' 92mm mounted midway up the rear panel would solve all of your problems.
- As for intake, I can make the "teeth" along the bottom of the base taller. That should increase airflow, too.

**Comment by jon-harper** [comment]
Couldn't find a CAD, but the spec sheet works as well. The fourth screw hole is a bit odd--the RSP-500 has an "extra" M4 screw hole in the middle. You'll be using that instead of the corner screw  hole near the Raspberry Pi (it would require a tray redesign). Here's what I mean:

![image](https://user-images.githubusercontent.com/11852387/181203819-b3cacc12-530d-49b6-9099-2415386c487f.png)

As always, let me know if you run into any issues.

---

P.S. I haven't modified the base yet to increase the intake "teeth" size. I'm pondering the idea of a universal PSU mount, so I'm hesitant to do too much right now.
